services:
  app:
    image: 'employee'
    container_name: employee
    ports:
      - 7000:7000
  prom:
    image: 'prom/prometheus'
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  graf:
    image: 'grafana/grafana'
    ports:
      - 8000:3000